name: waywing
description: "A wayland desktop shell made with flutter"
publish_to: "none"

version: 0.0.14

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Configuration parser
  config:
    version: ^0.0.13
    git:
      url: https://github.com/ross96D/config.dart
      tag_pattern: "{{version}}"
  config_gen:
    version: ^0.0.17
    git:
      url: https://github.com/Wishmater/config_gen
      tag_pattern: "{{version}}"

  miga:
    version: ^1.1.1
    git:
      url: https://github.com/ross96D/miga
      tag_pattern: "{{version}}"
  # Logger
  tronco:
    # path: ../tronco
    git:
      url: https://github.com/ross96D/tronco
      ref: 5ecd6268393c80358abf64c0a2270ba1ef4a1676

  niri:
    # path: ../../my/niri.dart
    version: ^1.0.0
    git:
      url: https://github.com/ross96D/niri.dart
      tag_pattern: "{{version}}"

  # Language utilities
  intl: ^0.20.2
  dartx: ^1.2.0
  args: ^2.7.0
  human_file_size: ^0.6.0
  # used to read audio themes index files
  ini: ^2.1.0
  # allow correct execution between async executions
  mutex: ^3.1.0
  # render notifications html subset
  flutter_html: ^3.0.0
  # used in the embeded third party package used in the AppLauncher freedesktop_entry
  collection: ^1.19.1
  # string matching algorithms
  fuzzy_string: ^1.0.0

  # Widgets / UI
  sliver_tools: ^0.2.12
  animations: ^2.0.11
  auto_size_text: ^3.0.0
  implicitly_animated_list: ^2.3.0
  multi_value_listenable_builder_typed: ^0.1.1
  motor: ^1.0.0-dev.4
  # color scheme creation
  flex_seed_scheme: ^3.5.1
  # icons
  material_symbols_icons: # ^4.0.0 # prefer using material symbols, that support parameters
    version: ^4.2873.2
    # path: ../material_symbols_icons
    git:
      url: https://github.com/Wishmater/material_symbols_icons
      tag_pattern: "{{version}}"
  flutter_mdi_icons: ^0.1.3 # Material Community Icons
  lucide_icons_flutter: ^3.1.0 # Lucide Icons, for some spice (mostly unused)

  # Native plugins
  path: ^1.9.1
  # directory/file watcher library
  watcher: ^1.1.2
  # cli colors
  chalkdart: ^3.0.5
  # interprocess comunication library for linux
  dbus: ^0.7.11
  # network manager
  nm: ^0.5.0
  # render icons from string as defined in xdg icons spec
  xdg_icons:
    path: vendor/xdg_icon
  flutter_svg: ^2.2.1
  # battery and other power options
  upower: # battery and other power options
    version: ^0.7.1
    git:
      url: https://github.com/ross96D/upower.dart
      tag_pattern: "{{version}}"
  # Linux window / shellLayer manager
  fl_linux_window_manager:
    version: ^2.0.9
    git:
      url: https://github.com/Wishmater/fl-linux-window-manager
      tag_pattern: "{{version}}"
  # for audio mixing
  pulseaudio:
    # path: ../pulseaudio.dart
    git:
      url: https://github.com/ross96D/pulseaudio.dart
      ref: ed2dcce81c8e2031192f23c5925209ab7e0da6dc
  # plays audio in notifications
  audioplayers: ^6.5.0
  sembast: ^3.8.5+1
  aria2c: ^0.0.5

  # code generation package
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  bitwarden_vault_api:
    # path: ../../repos/bitwarden_api
    version: ^0.0.2
    git:
      url: https://github.com/ross96D/bitwarden_vault_api
      tag_pattern: "{{version}}"
  freedesktop_secrets:
    # path: ../../my/freedesktop_secrets.dart
    version: ^0.0.1
    git:
      url: https://github.com/ross96D/freedesktop_secrets.dart
      tag_pattern: "{{version}}"
  http: ^1.5.0
  html: ^0.15.6
  hive_ce: ^2.15.1
  http_cache_client: ^1.0.4
  http_cache_hive_store: ^5.0.1
  http_cache_core: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  freezed: ^3.2.0
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true

dependency_overrides:
  intl: ^0.20.2
  meta: ^1.16.0
  # fl_linux_window_manager:
  #   path: ../fl-linux-window-manager
  # config:
  #   path: ../config.dart
  # config_gen:
  #   path: ../config_gen
